// <auto-generated />
using ApiDbContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDbContext.Migrations
{
    [DbContext(typeof(ApiDatabaseContext))]
    partial class ApiDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiDbContext.Entities.TaskParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParameterDescription")
                        .HasColumnType("text");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.Property<int>("ParameterOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterValue")
                        .HasColumnType("text");

                    b.Property<int>("TaskSetingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskSetingId");

                    b.ToTable("TaskParameters");
                });

            modelBuilder.Entity("ApiDbContext.Entities.TaskSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<string>("TaskFileName")
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .HasColumnType("text");

                    b.Property<string>("TaskPath")
                        .HasColumnType("text");

                    b.Property<string>("TaskUniqCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskSettings");
                });

            modelBuilder.Entity("ApiDbContext.Entities.TaskParameter", b =>
                {
                    b.HasOne("ApiDbContext.Entities.TaskSetting", "TaskSeting")
                        .WithMany("TaskParameters")
                        .HasForeignKey("TaskSetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskSeting");
                });

            modelBuilder.Entity("ApiDbContext.Entities.TaskSetting", b =>
                {
                    b.Navigation("TaskParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
